server:
  port: 8094
  servlet:
    session:
      timeout: 30m
    context-path: /sample-shop
spring:
  application:
    name: roncoo-pay-web-sample-shop
  mvc:
    view:
      prefix: /
      suffix: .jsp
logging:
  config: classpath:logback.xml