server:
  port: 8092
  servlet:
    session:
      timeout: 30m
    context-path: /gateway
spring:
  application:
    name: roncoo-pay-web-gateway
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
mybatis:
  mapper-locations: classpath:mybatis/mapper/*/*.xml
logging:
  config: classpath:logback.xml